### ISSUE TITLE
GradCam explanations plot error

### ISSUE THREAD

**Issue by daskcyber** [salesforce/OmniXAI#44]
Hi,

I'm using OmniXAI for classification purposes and for my project. I've used the method get_explanations to get a dict of GradCam explanation for one specific image.

Now i'm trying to plot the original image + explanations on it using PIL (instead of using ones presented in docs since i need this as object later) in this way:
```
...
exp=explanations.get_explanations(index=None)
gradcam_img=exp[0]['image']
Imag1 = PilImage.fromarray(gradcam_img)
plt.imshow(Imag1)
```

but i obtain the following error: TypeError: Cannot handle this data type: (1, 1, 3), <i8. If i try to use astype(np.uint8) it plots the originale image without explanations on it.

This is problem does not show up by doing the same procedure with lime explanations since i correctly obtain the image with explanations on it. How can i solve this?

**Comment by yangwenz** [comment]
Hi, you can directly plot the result using “plot” or “plotly_plot” functions implemented in the explanation object as shown in the tutorials, without converting it into Pil. Because the results are float values, it cannot simply be converted into Pil. If you are interested in how to do this, please check the implementation in the PixelImportance class in the “explanations” package.

**Comment by yangwenz** [comment]
https://github.com/salesforce/OmniXAI/blob/main/tutorials/vision/gradcam_torch.ipynb
https://github.com/salesforce/OmniXAI/blob/main/omnixai/explanations/image/pixel_importance.py
